defaults: &defaults
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  encoding: utf8

development:
  <<: *defaults
  database: sequelapp_development
  username: root
  password: root

test:
  <<: *defaults
  database: sequelapp_test
  username: root
  password: root

production:
  <<: *defaults
  database: sequelapp_production
  username: root
  password: root
